### ISSUE TITLE
Hi, amazing project

### ISSUE THREAD

**Issue by amaanq** [laytan/odin-tree-sitter#2]
I wanted to say thanks for these bindings! It's great that someone's using my Odin grammar for awesome stuff, and this might enable me to try out Odin in a domain I'm familiar with - will see if I can help out with stuff here, I want anyone-and-everyone to be able to use tree-sitter from whatever language they're comfortable with

**Comment by laytan** [comment]
Thank you so much! The grammar has been great. There have been some people in the Odin community (including me) making text editors, for which I made the bindings to try out integrating tree-sitter.
